<a href="https://colab.research.google.com/github/HwangGaHee/aipython/blob/main/0110%EB%AF%B8%EC%85%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

df=pd.read_excel("BoxOffice.xlsx")
df

,순위,영화명,개봉일,매출액,관객수,스크린수,상영횟수,대표국적,국적,배급사
0,1,명량,2014-07-30,135758208810,17615844,1587,188724,한국,한국,(주)씨제이이엔엠
1,2,극한직업,2019-01-23,139655543516,16266338,2003,292816,한국,한국,(주)씨제이이엔엠
2,3,신과함께-죄와 벌,2017-12-20,115727528087,14414658,1912,214631,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
3,4,국제시장,2014-12-17,110945002730,14264059,1044,212698,한국,한국,(주)씨제이이엔엠
4,5,어벤져스: 엔드게임,2019-04-24,122492181020,13977602,2835,246433,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
...,...,...,...,...,...,...,...,...,...,...
195,196,스파이,2013-09-05,24513098305,3436092,785,72805,한국,"한국,태국",(주)씨제이이엔엠
196,197,그것만이 내 세상,2018-01-17,27457704382,3420287,956,95444,한국,한국,(주)씨제이이엔엠
197,198,토이 스토리 4,2019-06-20,28763352540,3400623,1336,85913,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
198,199,돈,2019-03-20,28870244062,3389125,1431,120809,한국,한국,(주)쇼박스
199,200,맨 인 블랙 3,2012-05-24,27301520070,3379762,770,69538,미국,미국,한국소니픽쳐스릴리징브에나비스타영화㈜

In [22]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      200 non-null    int64
 1   영화명     200 non-null    object
 2   개봉일     200 non-null    datetime64[ns]
 3   매출액     200 non-null    int64
 4   관객수     200 non-null    int64
 5   스크린수    200 non-null    int64
 6   상영횟수    200 non-null    int64
 7   대표국적    200 non-null    object
 8   국적      200 non-null    object
 9   배급사     200 non-null    object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 15.8+ KB
None

In [24]:
print("대표국적별 영화편수 : ")
print(df['대표국적'].value_counts())

대표국적별 영화편수 :
한국    116
미국     82
일본      1
영국      1
Name: 대표국적, dtype: int64

In [25]:
print("대표국적이 '영국'인 데이터 : ")
print(df[df['대표국적']=="영국"])

대표국적이 '영국'인 데이터 :
      순위     영화명        개봉일          매출액      관객수  스크린수   상영횟수 대표국적  국적  \
194  195  어바웃 타임 2013-12-05  25312684300  3449451   568  67267   영국  영국

                     배급사
194  유니버설픽쳐스인터내셔널 코리아(유)

In [26]:
df.groupby("대표국적").min()

<ipython-input-26-c7316da265bc>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  df.groupby("대표국적").min()

,순위,개봉일,매출액,관객수,스크린수,상영횟수,국적,배급사
대표국적,,,,,,,,
미국,5,2005-12-01,21476688172,3379762,319,38456,미국,"(주)디스테이션,워너브러더스 코리아(주)"
영국,195,2013-12-05,25312684300,3449451,568,67267,영국,유니버설픽쳐스인터내셔널 코리아(유)
일본,172,2017-01-04,30628194346,3793790,947,88917,일본,메가박스중앙(주)플러스엠
한국,1,2005-01-27,22209675300,3389125,238,47155,한국,(주)넥스트엔터테인먼트월드(NEW)